title: "Sport Data Science Lab, Myongji University"
description: "Data Science for Sport."
theme: minima
baseurl: "/sport-data-science-lab"

header_pages:
  - about.md
  - research.md
  - publications.md
  - join.md
