title: "Sport Data Science Lab"
description: "Data Science for Sport."
theme: jekyll-theme-cayman
baseurl: "/sport-data-science-lab"
github:
  is_project_page: false

header_pages:
  - about.md
  - research.md
  - publications.md
  - join.md
